services:
  cs2-cache-retakes:
    image: joedwards32/cs2
    container_name: cs2-cache-retakes
    stdin_open: true
    tty: true
    environment:
      # Server configuration
      - STEAMAPPVALIDATE=0           # (0 - no validation, 1 - enable validation)
      - CS2_SERVER_HIBERNATE=0       # (Put server in a low CPU state when there are no players.
      - CS2_SERVERNAME=CS2 CACHE RETAKES — cs.bims.sh
      - CS2_PORT=27015               # (CS2 server listen port tcp_udp)
      - CS2_LAN=0                    # (0 - LAN mode disabled, 1 - LAN Mode enabled)
      - CS2_MAXPLAYERS=12            # (Max players)
      - CS2_PW                       # (CS2 server password)
      - CS2_CFG_URL=https://github.com/Bims-sh/cs2-cache-retakes/releases/latest/download/package.tar.gz
      - CS2_ADDITIONAL_ARGS=+exec cache-retakes.cfg
      # Game modes
      - CS2_GAMEALIAS=retakes
      - CS2_GAMETYPE=0                   # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_GAMEMODE=0                   # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_HOST_WORKSHOP_MAP=3437809122 # The workshop map to use. If collection is also defined, this is the starting map.
      # Logs
      - CS2_LOG=on                   # 'on'/'off'
    env_file: ".env"
    volumes:
      - ./cs2:/home/steam/cs2-dedicated
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
